### ISSUE TITLE
Investigate and fix rounding inconsitencies in fee sweeper

### ISSUE THREAD

**Issue by Xeonus** [BalancerMaxis/protocol_fee_allocator#132]

**Comment by Tritium-VLK** [comment]
See https://docs.google.com/spreadsheets/d/19T7Wsj0l40JCQJT_t0c6uFmHoZAMHdMLjOW3HVbcPew/edit#gid=1497834922 for current work comparing run results. note this is a copy of teh sheet/not shared with users.

**Comment by Tritium-VLK** [comment]
The theory was that inconsitancies came from an interaction between rerouting and redirection phases.  Next round there will be no redirection so can test that.
