### ISSUE TITLE
feat: import `build_core_pools` from `bal_addresses` submodule instead of reading the raw `core_pools.json`

### ISSUE THREAD

**Issue by gosuto-inzasheru** [BalancerMaxis/protocol_fee_allocator#99]

**Comment by Tritium-VLK** [comment]
@gosuto-inzasheru it may not hurt to do/test this and rerun.  Not sure how stale the core pools list was from your run last night.

**Comment by gosuto-inzasheru** [comment]
decided with @Tritium-VLK to close this; it actually makes more sense to have the core pools json go through a proper pr review process instead of generating it on the fly.
